# Generated by Django 5.2.4 on 2025-09-19 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_landlordrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkrequest',
            name='due_amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='linkrequest',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='linkrequest',
            name='property_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='linkrequest',
            name='rent',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='linkrequest',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='landlordrequest',
            name='status',
            field=models.CharField(choices=[('not_initiated', 'Not Initiated'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_initiated', max_length=15),
        ),
        migrations.AlterField(
            model_name='linkrequest',
            name='status',
            field=models.CharField(choices=[('not_initiated', 'Not Initiated'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='not_initiated', max_length=15),
        ),
    ]
