# Generated by Django 5.2.4 on 2025-09-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_customuser_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offlinetenants',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
