# Generated by Django 5.2.4 on 2025-09-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_offlinetenants_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linktenantlandlord',
            name='due_amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='offlinetenants',
            name='due_amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
