# Generated by Django 5.2.4 on 2025-09-21 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_linktenantlandlord_due_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkrequest',
            name='meter_rate',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='linkrequest',
            name='meter_reading',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='linktenantlandlord',
            name='meter_rate',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='linktenantlandlord',
            name='meter_reading',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='offlinetenants',
            name='meter_rate',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='offlinetenants',
            name='meter_reading',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
