# Generated by Django 5.2.4 on 2025-09-21 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_linkrequest_meter_rate_linkrequest_meter_reading_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billing',
            old_name='current_reading',
            new_name='meter_reading',
        ),
    ]
