# Generated by Django 5.2.4 on 2025-09-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_rename_current_reading_billing_meter_reading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='meter_reading',
        ),
        migrations.RemoveField(
            model_name='linktenantlandlord',
            name='meter_reading',
        ),
        migrations.RemoveField(
            model_name='offlinetenants',
            name='meter_reading',
        ),
        migrations.AddField(
            model_name='billing',
            name='current_meter_reading',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='billing',
            name='starting_meter_reading',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='linktenantlandlord',
            name='starting_meter_reading',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='offlinetenants',
            name='starting_meter_reading',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='billing',
            name='amount_paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='billing',
            name='meter_image',
            field=models.ImageField(blank=True, null=True, upload_to='meter_images/'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='meter_rate',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='billing',
            name='misc_charge',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='billing',
            name='previous_due_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='billing',
            name='previous_meter_reading',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='billing',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('generated', 'Generated'), ('unpaid', 'Unpaid'), ('partial', 'Partial'), ('paid', 'Paid')], default='pending', max_length=25),
        ),
        migrations.AlterField(
            model_name='linktenantlandlord',
            name='due_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='offlinetenants',
            name='due_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='offlinetenants',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
