# Generated by Django 5.2.4 on 2025-09-24 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_billing_meter_reading_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linkrequest',
            old_name='meter_reading',
            new_name='starting_meter_reading',
        ),
    ]
