# Generated by Django 5.2.4 on 2025-09-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_billing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='current_meter_reading',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
