# Generated by Django 5.2.4 on 2025-09-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_billing_current_meter_reading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='bill_amount',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='note',
        ),
        migrations.AlterField(
            model_name='billing',
            name='meter_rate',
            field=models.IntegerField(default=0),
        ),
    ]
