# Generated by Django 5.2.4 on 2025-09-26 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_billing_bill_amount_remove_billing_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='total_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
