# Generated by Django 5.2.4 on 2025-09-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_billing_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkrequest',
            name='meter_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='linktenantlandlord',
            name='meter_rate',
            field=models.IntegerField(default=0),
        ),
    ]
