# Generated by Django 5.2.4 on 2025-09-26 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_linkrequest_meter_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='starting_meter_reading',
        ),
    ]
