# Generated by Django 5.2.4 on 2025-09-26 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='meter_image',
            field=models.ImageField(blank=True, null=True, upload_to='meter_photos/'),
        ),
        migrations.CreateModel(
            name='TenantDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_type', models.CharField(choices=[('Offline', 'Offline'), ('Online', 'Online')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('document', models.FileField(upload_to='tenant_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('offline_tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.offlinetenants')),
                ('online_tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
