# Generated by Django 5.2.4 on 2025-09-26 12:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_billing_meter_image_tenantdocument'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenantdocument',
            old_name='document',
            new_name='file',
        ),
        migrations.RemoveField(
            model_name='tenantdocument',
            name='title',
        ),
        migrations.AddField(
            model_name='tenantdocument',
            name='document_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tenantdocument',
            name='tenant_type',
            field=models.CharField(choices=[('offline', 'Offline'), ('online', 'Online')], max_length=10),
        ),
        migrations.AlterField(
            model_name='tenantdocument',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
