# Generated by Django 5.2.4 on 2025-09-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_rename_document_tenantdocument_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantdocument',
            name='document_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tenantdocument',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
