# Generated by Django 5.2.4 on 2025-09-27 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_tenantdocument_document_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billing',
            old_name='meter_image',
            new_name='meter_photo',
        ),
    ]
