# Generated by Django 5.2.4 on 2025-10-01 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_rename_meter_image_billing_meter_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='offline_tenant_access',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='wants_landlord',
        ),
    ]
