# Generated by Django 5.2.4 on 2025-10-03 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_remove_customuser_offline_tenant_access_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkrequest',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
