# Generated by Django 5.2.4 on 2025-10-03 16:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_linkrequest_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Enter 10 digit phone number, numbers only.', max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='Phone number must be exactly 10 digits.', regex='^\\d{10}$')]),
        ),
    ]
